name: Publish Rust Docs

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust versions
        run:  rustup show

      - name: Rust cache
        uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0

      - name: Build rustdocs
        run:  SKIP_WASM_BUILD=1 cargo doc --all --no-deps

      - name: Make index.html
        run:  echo "<meta http-equiv=refresh content=0;url=cumulus_client_collator/index.html>" > ./target/doc/index.html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
